### ISSUE TITLE
Hashicorp Vault, AWS KMS, Chef/Ansible Vault, Consul [Hack Session]

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#137]
A hack session mostly on storing & distributing secrets. 

Disclaimer: I know very little - we'll just play and learn. Some afternoon this week (starting 8 Aug) or the next would be good for me. 

Just  👍  if interested

**Comment by vervelak** [comment]
👍

**Comment by sonaht** [comment]
Goes without saying...YES :+1:

**Comment by gvre** [comment]
+1

**Comment by sonaht** [comment]
Guys I will suggest the following to make things a bit more interesting:

To make this hack session count I would suggest we divide (or pick and choose) some issues from the above title and create a small (minute even) presentation or a working case as such in order to present it to the fellow hack session members.

I would definitely do ansible vault and will dive into consul as well, as this was meant to be done long time ago.

I would also suggest to plan this for the week after the next since some (if not all) of us will be on our well earned holidays !!!

Opinions / Arguments / Ideas always welcomed.

**Comment by kapolos** [comment]
Did this session happen or is it still open?

**Comment by gsaslis** [comment]
How about setting this on Thursday, September 1st?

**Comment by kapolos** [comment]
Good for me, depending on the time.

**Comment by sonaht** [comment]
Hello everyone..

This hack session will happen on Thursday, 1st of Sep, at 20.00

Usual place @ office12 (http://goo.gl/N5m9T5)

Will create a meetup.com hack session as well.

**Comment by sonaht** [comment]
This was perfectly done, closing it
