### ISSUE TITLE
Video Recording / Streaming / Broadcasting of meetup events

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#186]
This is a topic that has come up over and over. I am opening this issue, so we can keep it as a point of reference for the discussion around it. 
Common cases this issue has been reported (more than once in each one) include: 

1. people being out of town and wanting to attend virtually
2. people living somewhere else wanting to attend virtually
3. people not being to attend at the specific day & time, neither physically nor virtually, and wanting to hear the talks at some other time
4. people within DevStaff feeling the topic could interest a broader audience

During every discussion I've attended so far, we've agreed not to bother with any type of recording / live streaming / broadcasting the meetups. 

The main reasons (I remember right now) were that: 

- it takes a lot of work to do it properly (high quality recording equipment setup + post-event processing) and 
- it falls a little outside the scope of our (entirely informal) "mission", which is "to bring people who are passionate about software and technology closer together"  

Personally, I feel it is also taking away from the value someone gets from attending a DevStaff meetup. (IMHO, most of the value lies in meeting others like you, who live in the same place as you and that you share common interests with). Any virtual attendee would be missing out on this.  

Please feel free to add your own comments below and build a case for / against *one* (or even all) of the options. Clearly, each option is quite different from the others, and comes with its own pros/cons.

**Comment by maounis** [comment]
I agree that the "networking" is probably the most important thing of those meetups but still every talk has some value for some others out there that cannot attend for any reason.

OpenCoffee Heraklion is doing this and I see no problem with it. I know that for every topic there is a ton of talks on YouTube but I don't underestimate the unique value of every speaker.

So unless the speaker states otherwise I say that it is a good idea to try.

**Comment by mijalis** [comment]
I think that there should be an option at least for recording and offline
viewing.
In addition to the reasons mentioned above it would also be great for
archiving and future reference.

Live streaming and remote attending will probably be more difficult to
manage.

Στις 7 Ιουν 2017 9:57 μ.μ., ο χρήστης "Frank Maounis" <
notifications@github.com> έγραψε:

**Comment by sonaht** [comment]
Again in principle I believe this to be a good idea, that is the ability to record and produce something  relating to the live meetup.

Given that the speakers do not have an issue with this I would agree, alas I strongly believe that it requires a lot of time from the person(s) who decide to actually do this. If we are to do it, then it should be done to a certain level. 

And the real question will eventually be if the ones deciding to undertake such task are prepared to commit for the next few meetups at least ? (I say again the time required will be substantial).

**Comment by DaKnOb** [comment]
What we could do is try it. Start with live streaming first, and then maybe move to recording too. See if it works for a meet up, maybe two, and then decide.
If we want to do this, I volunteer to live stream an event, given that I am in Heraklion at the time.
If we decide to do this, people with an external web camera (like the Logitech ones) that support a minimum of 720p, and people with USB wireless microphones could certainly help though. :P

**Comment by sksksksk** [comment]
The whole point for the meetups (IMHO) is the face to face contact with the speaker and the participants. If this is less important, there is plenty of video material available to view and get acquainted with technology. It makes no sense for someone to want to view these specific talks.
I believe that the video recording and streaming has no real value to offer.

**Comment by kabitakis** [comment]
I see two main reasons for having some kind of streaming/recording:
1. Future reference. The community is about to close its 2nd year. I'd love we have some early videos 5-10 years from now.
2. If people away/abroad want to watch our presentations I see no reason why we don't offer this option to them. We should feel honoured of such requests and at least try to provide this option.

Now, if there are people who will not attend because of this, be it. It's their choice to make. We could add message to every video and let them know that WE WANT THEM ON SITE and even if they're watching this one, they should try to be there next time.

I understand the idea is difficult to be implemented and there are logistics to be considered, however we could keep it as simple as:
1. Recordings/streaming are **permitted** in regular basis. One speaker can change that rule.
2. Recordings/streaming are **not provided** in regular basis.
3. Let's try to find people who could take care of such a task. It could be a different person in each event. The same way we do it with pizzas and beers. So, for every event we should call for 1) speakers, 2) pizza heroes, 3) video ninjas.

Last but not least, we should also find a way to create a promo video of some kind.

**Comment by irinikp** [comment]
I agree with all the above! Let's do this!

**Comment by kabitakis** [comment]
Σήμερα κοιτάζοντας στο fb τα νέα posts των φίλων μου είδα ένα από τα πολλά videos που ανεβάζει ένας αγαπημένος μου μουσικός από ένα gig των προηγούμενων ημερών. Τα παιδιά είναι από τα καλύτερα blues/jazz σχήματα που μπορεί κάποιος να ακούσει στην Ελλάδα κ φυσικά δε χάνω την ευκαιρία να τους ακούσω όταν βρίσκονται, με αυτή ή άλλες συνθέσεις, στην Κρήτη. Αν είναι στα Χανιά δλδ, θα πάω στα Χανιά για να τους ακούσω.

Δείτε το video εδώ: https://www.facebook.com/asterios.papastamatakis/posts/1375204179200940

Το video δείχνει στο μεγαλύτερο μέρος του ένα drum solo,  το οποίο είναι πολύ καλό αλλά σίγουρα μπορείς να βρεις καλύτερα στο youtube, ενώ η ποιότητα εικόνας κ ήχου είναι χάλια. Οπότε τελικά τι έχει σημασία σε αυτό το video για μένα;

1. Λέει ότι παίζουν ξανά απόψε κ αν ήμουν Αθήνα θα πήγαινα να τους ακούσω.
2. Το video μου θύμισε ότι πρέπει να πάω να τους ακούσω.
3. Είναι άνθρωποι που μετά το gig θα πιουν μια μπύρα εκεί στο bar κ θα κάτσεις μαζί τους 10-15' να συζητήσεις.
4. Οτιδήποτε άλλο βρίσκω στο youtube είναι παλιό ή/και απίθανο να ακούσω live λόγω τοποθεσίας.
5. Ακόμα κ αν είχα video με μεγαλύτερο μέρος του gig, θα ήθελα να είμαι εκεί

Δεν κάνω κάποια σύγκριση. Χρησιμοποιώ το github issue σαν thought repo.

**Comment by zakkak** [comment]
Let's not forget that in case of recordings we should **license** the video as well (with the license each speaker wants for his part of the talk).

Additionally we must notify **each** speaker that we plan to stream/record the talk and only if he agrees we can do it, otherwise his part can not be _aired_.

**Comment by gsaslis** [comment]
closing this, since there was a decision in december org meetup to stream (but not record) meetups for some months and re-evaluate later.
