### ISSUE TITLE
Hack-Session RSVPs

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#305]
Hello all,

It is common practice for some of the people in the community to RSVP in Hack-sessions and not show up at the event. This is causing 2 kind of issues the way I see it:

1. People that want to attend are left out even though there is enough space for them in the end.
2. Organizers some times search for more suitable venues to accommodate the larger number of participants with no real need.

I open this issue to discuss possible ways that could improve the situation, hopefully without introducing other negative effects.

One approach would be to give counter-motives, e.g. people that have RSVPed and do not show up cannot RSVP in the following X hack sessions. Another approach would be to make RSVPing something more than just pressing a button, e.g. donating a symbolic amount to the venue, or buying the speaker a coffee, beer whatever. If you can thing of other possible ways please write them below.

Please keep in mind that the enforcement of such policies should be automated.

**Comment by gsaslis** [comment]
Thanks for raising this issue @zakkak !!

 Yes, this has certainly happened more than once!!

I like yourideas and the proposal for an automated way of enforcement and i almost want to suggest:

You pay 5 euro to reserve a space - you get the 5 euro back when you show up.

I just have some reservations on whether this causes any problems with invoices having to be issued etc...
E.g. how do we get the money from meetup.com ?

**Comment by zakkak** [comment]
Meetup appears to be able to handle event fees through paypal. That said charging for the event is achievable without much effort.  I am not sure though what happens with paypal's fees in case of refunding.

Regarding the invoice, if the money go to the venue then I guess it is not a big issue for them to issue an invoice. However, there are venues where this might not be possible, e.g. hosting an event in the University, in a coffee shop, in someone's house, etc.

If the money go to the Organizer/Speaker then I am not sure if we can handle this through some donation scheme.

In general I am a bit skeptical about getting money in the game, since this might discourage some people from attending.

Googling around I have found various policies acting on the "no-shows", but all of them require human intervention. There are policies with point systems where not showing up assigns the person some penalty points and after a certain threshold the said person is removed from the meetup group. There are policies where "no-shows" get added to the waitlist, so that they can only attend if there is enough space for everyone else. There are also schemes where instead of penalizing "no-shows" they make it harder to RSVP requiring feeling up forms/questionnaires.

I can only imagine implementing the last one in an automated manner were filling a form will finally give you a link to RSVP.

**Comment by kabitakis** [comment]
For Office12 I'm thinking of a small fee per person (2-5€). If every single one shows up, half of the amount will be donated back to the community or a predefined cause. And I say half because if there are invoices, taxes and stuff will be applied.
😄

**Comment by gsaslis** [comment]
Let me add some context / more background information / history. 

So, before we even are in a position to *decide* what to do with no shows, we have to know "who are the no shows". 

However, even this is a problem for the bigger, monthly, meetups when there are a lot of new faces. We don't always know who the people are that turn up (and that's not necessarily a bad thing... see below), so we can't "flag" them accordingly ... much less if they RSVPed YES for the first time but never came. 

Couple that with the fact that some of our group members don't use their real names (but usernames, abbreviated last names, etc.) and you get an idea of how difficult it is to even know "who showed up". 

Back in the first year or so, one idea I had was to print name badges and I left them at the entrance and asked folks to pick up their badge as they walked in. The badges that nobody picked up were our "no shows". 
(back then, meetup.com [used to offer an easy way to do that](https://meetupblog.typepad.com/meetup-hq-blog/2009/12/by-jesse------hey-meetupperswe-now-have-an-easy-way-to-automatically-print-name-tags-for-everyone-attending-a-meetup.html)... unfortunately it does not any more - or i have found no way to get to that page )

These days it seems Meetup.com just allows organizers to go through event attendees *after the event* and flag some who said "yes" - but didn't go - as "no shows". I haven't found any way of acting on that information though (even manually) For example, when creating a new event there is no "don't allow frequent no shows" option. 

frankly - unless someone wants to step up and volunteer "owning" that (i.e. both keep track of no shows, but also turn them down next time they RSVP to a hack session, so that places stay open) i don't see any other way of this really working... 

and I would be VERY glad if someone stepped up to solve this, because it's a real problem!

**Comment by ealefrag** [comment]
Just a couple of thoughts here. I think the bigger issue has to do with Hack-Sessions' RSVPs (which by the way is the actual title of the issue here :nerd_face: ). Having been excluded from several Sessions in the past (I am not the fastest guys in doing RSVPs), I can imagine that there must had been some available slots at some point, but anyway this is my intuition. So, mainly, I would say that goes first  as the participants' slots are limited. 

As for the charging, I agree that everyone is going to respect more the whole process. However, we have to be transparent in advance in terms of where the remaining money of the community will be used for. One the other hand, if we involve money in the process we will probably need to set up a regulatory structure, or even a single "treasurer", but again this opposes to how devstaff works/operates already. 

So, I would say something like warning everyone (a couple of times if needed) during the RSVP process, regarding his/her exclusion and the actual penalty for not attending while being RSVP. Or even let anyone has his own first unpunished time.

**Comment by gsaslis** [comment]
I am currently attending a BarcelonaJUG meetup.

They charge 2 eur per RSVP which get paid into a paypal account.

Whoever turns up, puts their name down in a form and gets full refund via paypal.

**Comment by zakkak** [comment]
The bad thing is that someone needs to go through the list and issue the refunds...

**Comment by zakkak** [comment]
Now that we are using open collective it seems much easier to enforce the fee thing, the only problem is that lately we don't have so many hack sessions happening :) 

That said I am closing this as IMHO it's no longer an issue.
