### ISSUE TITLE
Docker and alternatives

### ISSUE THREAD

**Issue by npapnet** [devstaff-crete/DevStaff-Heraklion#34]
This might be interesting to non-web developers. 

When developing an application external libraries and maybe sometimes operating systems are assumed. However, some times things break (see updates/upgrades). 
Docker seems to offer an attractive proposition to develop and mainly deploy applications without worrying too much about OS, or libraries in the system. 

Has anyone used something Docker or something similar? 
Any practical experience on what is achievable/limitations?

**Comment by sonaht** [comment]
Hello

Pls make a point in adding a description, as well as points to be discussed, and in general make this appealing to anyone that might want to thumb up...

The better this is explained the more votes it might get 

ty

**Comment by DaKnOb** [comment]
:+1:

**Comment by DaKnOb** [comment]
BTW: I've used Docker a lot and I know by fact that *several* large companies use exclusively containers. 

This talk can be about Docker, what it is, what it offers, what does it too best, how you can deploy and manage it, etc.

**Comment by gsaslis** [comment]
:+1: also played around a bit with Docker, looks very promising, but we're not using it in prod yet... would definitely be interested to learn more on the subject!

**Comment by DaKnOb** [comment]
Not using it **yet**? Gosh, you're missing the Docker Revolution!!

Okay, truth be told, Docker is extremely useful when you are in a larger scale. I'm not talking millions, but even in hundreds of servers. It can reduce cost dramatically, and it can also provide good fault tolerance.

**Comment by gsaslis** [comment]
yeah, well, truth be told it IS a bit of a trend... and we're not *that* trendy!

**Comment by sonaht** [comment]
Do not wish to open a massive argument here, but it is over stated as such. Consider the fact that "ansiible" (or similar tools) for example can do exactly the same and more, irrespective of cloud provider, etc etc. It is a trend and a good one i might add... (not a great fan of it)

**Comment by DaKnOb** [comment]
Well, most people think of Docker as a tool to provision stuff or change configurations. This is not Docker, this is Ansible. :P

Docker can also allow running multiple instances of several containers over many servers, all kept inside their own little "sandbox". 

With good orchestration, like with Google's Kubernetes, you can achieve great things.. You can move within seconds all services to new servers, start new servers and populate them instantly with required stuff, move jobs with high RAM demand and high CPU demand to the same server so as not to waste any, and in general make rapid changes to your infrastructure so you can achieve more with less. All this, with a layer of "security" with the "sandbox" and a layer of automated dependency handling. 

With Ansible, if you had to move your MySQL across servers depending on its load, you'd be installing and purging the `mysql` package all the time. With docker, you just start a new process. Also, after moving things around a few hundred times, the VMs would be left with uninstalled dependencies, and in general too much garbage (unless done right) that would cause some overhead.

**Comment by sonaht** [comment]
I understand the "sandbox" mentality, but it is just another name for having many vms inside your cloud, (public or private) etc.

So in a sense it is creating multiple instances (containers) on one or more servers, it eventually ends up being deploying/provisioning. The idea is the same if we abide to certain rules.

On the mysql thingy I need to see it to believe it. Why would I need to move my(mysql)db across servers? How would I do that unless my app knows about multiple servers ? (do I not have clusters OR multi master/multi slave db setup?). Ansible will help provision extra master/slaves in limited time, that in effect will help ease the load. Assuming a DB of hundreds of GBs ... I can hardly see provisioning an extra container solving the issue.  

There is a place in the IT world for tools like Docker or terraform.io (check this...it is great) as well as tools like ansible, puppet and the like. Specific custom tools that Google might use relate to different infrastructure sizes, maybe not applicable to the rest. Size and cost, dictate the use.

As a final remark, ansible will actually work on top of docker as soon as the container is deployed in order to configure. Having said, I could deploy(create/provision) the new "container" with ansible, as well as configure it afterwards with ansible again. Addfing an extra layer of technology is not necessarily bad, not always needed tho.

We can discuss this in person, as I see we will go on for hours "arguing", and I am very happy about this as well.

**Comment by DaKnOb** [comment]
Well, a great combination is Docker + Ansible, I have to admit this. I even use it. :-)

The two main points are:

* You get more traffic in Asia in your web application. You instantly move some of your web servers to Asia to reduce the RTT between the client and your end point. From that point, you may move a copy of your database too, for better backend performance. Sure, you can start VMs with the `webserver.iso` you have but this would require renting more servers. What if you could actually increase the density of your web servers there and don't need new ones? [I need to explain this better in person :-) ]

* You have 10 VMs. One of them is your Mail Server, the other your MySQL, the rest your Web Servers. What if you could bundle, --without conflicts--, your MySQL server (a RAM and CPU demanding task) and your Mail Server (a resource-friendly task) in the same VM, bundle a few web servers to the same VM and end up needing 3-4 VMs instead of 10? Currently, the most executed instruction in a CPU is the `idle` one. It has nothing to do. Most physical RAM pages are either unmapped or unallocated. Sure, you can make it work with just Ansible and VMs, but Docker enables you to push CPU and RAM close to 100% and actually make sure of the resources you rent / own **without creating any conflicts between the software running on the same VM / host**.

**Comment by kabitakis** [comment]
wow guys! we need to talk about this soon or else I see this topic going large-scale.
So.. :+1:

**Comment by sonaht** [comment]
:+1:

**Comment by maounis** [comment]
Hi to all.

I know very little about Docker but it seems that 

- Docker Compose
- Docker Machine
- Docker Swarm

are very interesting tools and can be combined together to do great things.

Also the list of container orchestration tools by third parties is growing fast which shows that more is coming.

So :+1:

**Comment by msti** [comment]
:+1: 
I would love to see a hands on session or use cases of docker applications

**Comment by webdevgr** [comment]
:+1:

**Comment by kargakis** [comment]
If you are interested in managing applications running in containers you may want to have a look at Openshift v3, a full-blown PaaS based on Kubernetes:
```
git clone https://github.com/openshift/origin
cd origin
make clean build
vagrant up; vagrant ssh
```
and then have a look at the [sample-app](https://github.com/openshift/origin/blob/master/examples/sample-app/README.md#application-build-deploy-and-update-flow) example.

Shameless plug as I am one of the developers:)

**Comment by maounis** [comment]
@kargakis Wow. I knew Openshift but just read a lot more. It would be very interesting to compare this with Docker Control Plane that it was just announced in Barcelona.  

Of course Docker Control Plane is not going to be free :)

**Comment by DaKnOb** [comment]
Turns out the daily chat on gitter about docker didn't convince people to up vote this.. :P

**Comment by markop** [comment]
:+1:

**Comment by markop** [comment]
:+1:

**Comment by irinikp** [comment]
👍

**Comment by sonaht** [comment]
wow this is really really old. R we still interested in this ?

**Comment by gsaslis** [comment]
Yes, let’s :thumbsup:
